version: '3.7'
  
services:
  IRISHEALTH:
    container_name: irishealth
    image: intersystems/irishealth:2019.1.0.510.0-1
    hostname: IRISHEALTH
    environment: 
     ICM_SENTINEL_DIR: /external
     ISC_DATA_DIRECTORY: /external/irishealth
    volumes: 
     - /data/docker/storage:/external
    command: --key /external/iris.key
    ports:
     - 51773:51773
     - 52773:52773
     - 9000:9000
